all:
  children:
    nxos:
      hosts: null
    ios:
      hosts:
        test-ngt-frsw-001: null
        cat-vswitch: null
    vswitch:
      hosts:
        sandbox: null
    cumulus:
      hosts: null
    fortigate:
      hosts: null
      vars:
        ansible_connection: local
